hwi_oauth:
    firewall_names: [main]
    resource_owners:
        google:
            type: google
            client_id: "%env(GOOGLE_CLIENT_ID)%"
            client_secret: "%env(GOOGLE_CLIENT_SECRET)%"
            scope: "email profile"
            paths:
                email: email
                profilepicture: picture
                firstname: given_name
                lastname: family_name