# config/packages/security.yaml
security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User:
            algorithm: auto
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_EMPLOYEE: [ROLE_USER]
        ROLE_CITOYEN: [ROLE_USER]
    providers:
        pdadmin_auth:
            entity:
                class: App\Entity\User
                property: email
        oauth_provider:
            id: App\Security\MyOAuthUserProvider
        chain_provider:
            chain:
                providers: [pdadmin_auth, oauth_provider]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: chain_provider
            lazy: true
            user_checker: App\Appaydin\PdUser\Security\UserChecker
            entry_point: form_login # Set form_login as the entry point
            form_login:
                use_referer: true
                login_path: security_login
                check_path: security_login
                success_handler: App\Security\AuthenticationSuccessHandler
            logout:
                path: security_logout
                target: front_home
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week
                path: /
            oauth:
                resource_owners:
                    google: "/login/check-google"
                login_path: security_login
                failure_path: security_login
                oauth_user_provider:
                    service: App\Security\MyOAuthUserProvider
                default_target_path: back_dashboard
    access_control:
        # - { path: ^/auth/login$, role: PUBLIC_ACCESS }
        # - { path: ^/auth/register, role: PUBLIC_ACCESS }
        # - { path: ^/auth/resetting, role: PUBLIC_ACCESS }
        # - { path: ^/admin/dashboard, roles: ROLE_ADMIN }
        # - { path: ^/citoyen/dashboard, roles: ROLE_CITOYEN }
        # - { path: ^/employee/dashboard, roles: ROLE_EMPLOYEE }
        # - { path: ^/, roles: PUBLIC_ACCESS }
        # - { path: ^/, role: ROLE_USER }