security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User:
            algorithm: auto
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_EMPLOYEE: [ROLE_USER]
        ROLE_CITOYEN: [ROLE_USER]
    providers:
        pdadmin_auth:
            entity:
                class: App\Entity\User
                property: email
        oauth_provider:
            id: App\Security\MyOAuthUserProvider
        chain_provider:
            chain:
                providers: [pdadmin_auth, oauth_provider]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: chain_provider
            lazy: true
            user_checker: App\Appaydin\PdUser\Security\UserChecker
            entry_point: form_login
            form_login:
                use_referer: true
                login_path: security_login
                check_path: security_login
                success_handler: App\Security\AuthenticationSuccessHandler
            logout:
                path: security_logout
                target: front_home
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week
                path: /
            oauth:
                resource_owners:
                    google: "/login/check-google"
                login_path: security_login
                failure_path: security_login
                oauth_user_provider:
                    service: App\Security\MyOAuthUserProvider
                default_target_path: back_dashboard
                failure_handler: security.authentication.failure_handler
            access_denied_handler: App\Controller\SecurityExceptionController
    access_control:
        # Public access routes
        - { path: ^/auth/login$, role: PUBLIC_ACCESS }
        - { path: ^/auth/register, role: PUBLIC_ACCESS }
        - { path: ^/auth/resetting, role: PUBLIC_ACCESS }
        - { path: ^/login, role: PUBLIC_ACCESS }
        - { path: ^/$, role: PUBLIC_ACCESS }
        
        # Admin routes
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/back, roles: ROLE_ADMIN }
        
        # Citoyen routes
        - { path: ^/front, roles: ROLE_CITOYEN }
        - { path: ^/profile, roles: [ROLE_CITOYEN, ROLE_ADMIN, ROLE_EMPLOYEE] }
        
        # Employee routes
        - { path: ^/employee, roles: ROLE_EMPLOYEE }