# config/packages/security.yaml
security:
  enable_authenticator_manager: true

  password_hashers:
    Symfony\Component\Security\Core\User\InMemoryUser: plaintext

  providers:
    in_memory:
      memory:
        users: []

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      provider: in_memory
      lazy: true
      security: false  # Remplace 'anonymous: true'

  access_control:
    - { path: ^/avis, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: PUBLIC_ACCESS }