controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
# authorization:
#     resource: "@PdUserBundle/Resources/config/routing.yaml"
#     prefix: /auth
